services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:3000/health').then(r => r.ok ? process.exit(0) : process.exit(1))",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    # Add volume mounts for persistent data
    volumes:
      - sqlite_data:/usr/src/app/db
      - app_data:/usr/src/app/data
# Define named volumes
volumes:
  sqlite_data:
  app_data:
